#!/bin/bash
#
# A simple script to add lateral gaps to Aerospace windows.
# Useful on big monitors.
#
# Usage:
# "aerogap <value>"
# If a value is unspecified, a default is set.
#

set -e

size="${1:-10}"

# Edit Aerogap file so gaps have a specified size
sed -i '' 's/^outer\.left = .*/outer.left = [{monitor.main = '$size'}, 10]/; s/^outer\.right = .*/outer.right = [{monitor.main = '$size'}, 10]/' ~/.config/aerospace/aerospace.toml

# Reload aerospace
aerospace reload-config

